tuple1 = (('a', 23),('b', 37),('c', 11), ('d',29))
print(f"Original tuple: {tuple1}")
list1 = list(tuple1)
sorted_list = sorted(list1, key=lambda x: x[1])
sorted_tuple = tuple(sorted_list)
print(f"Sorted tuple: {sorted_tuple}")